languageCode = "en-us"
title = "Gravpher"
baseurl = "https://goujianing.ml/"
disableKinds = ["sitemap", "RSS"]

[params]
  name = "Jianing Gou(George Gou/Gravpher)"
  about = " &nbsp;&bull;&nbsp; <a href='http://www.apm.cas.cn/' target='_black'>Innovation Academy for Precision Measurement Science and Technology, CAS</a> &nbsp;&bull;&nbsp; Open Sourcer/ Geophysics and Geodesy"
  copyright = "Do one thing at a time, and do well - George&Bird Inc 2019~forever"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""
  

[[params.social]]
  medium = "Academic"
  icon = "university"
  link = "https://goujianing.ml/home"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "mailto:goujianing19@mails.ucas.ac.cn"

[[params.social]]
  medium = "blog"
  icon = "edit"
  link = "https://goujianing.ml/blog"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/George-Gou"
  
[[params.social]]
  medium = "Link"
  icon = "link"
  link = "https://me.goujianing.ml/link/"



